[flake8]
exclude = .git, *migrations*, .tox, dist, htmlcov
max-line-length = 88
select = C,E,F,W,B,B950
ignore = E203, E231, E501, W503, W291, W293

[tox]
envlist = {py38, py39, py310, py311, py312}-django{42}, pylint

[testenv]
setenv =
    DJANGO_SETTINGS_MODULE = testauth.settings_aa4.local

deps =
    !django42: allianceauth<4
    django42: allianceauth>=4.9.0
    coverage
    django-eveuniverse
    factory_boy

commands_pre =
    pip list

commands =
    coverage run runtests.py jaystools -v 2
    coverage xml
    coverage report

[testenv:pylint]
deps =
    django-eveuniverse
    pylint
    pylint-django

commands =
    pylint --load-plugins pylint_django jaystools

