# Generated by Django 4.2.23 on 2025-09-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The filter name that is shown to the admin.', max_length=500)),
                ('description', models.CharField(help_text='The filter description that is show to end users.', max_length=500)),
                ('days', models.IntegerField(default=30, help_text='The number of days to look back to count recruitments')),
                ('recruitments_needed', models.IntegerField(default=1, help_text='The number of recruitments to pass the filter')),
            ],
            options={
                'verbose_name': 'Smart Filter: Number of recruitments in time period',
                'verbose_name_plural': 'Smart Filter: Number of recruitments in time period',
            },
        ),
    ]
