# Generated by Django 4.2.23 on 2025-09-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaystools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSkillPointFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='The filter description that is show to end users.', max_length=500)),
                ('sp_threshold', models.PositiveBigIntegerField(help_text='The filter will work for character that has less than the amount specified')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
