# Generated by Django 4.2.23 on 2025-09-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaystools', '0002_characterskillpointfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterskillpointfilter',
            name='ignore_alts',
            field=models.BooleanField(default=False, help_text='Ignore the alts and apply filter only to the main'),
        ),
    ]
